// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxpblfcwowouusobrvdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4cGJsZmN3b3dvdXVzb2JydmR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MTc4MjIsImV4cCI6MjA1NzE5MzgyMn0.4Qc-sR7O0HzK0owOW9X6YlnCu__kIMiOpl0sd4yB9dA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);